name: canvas-batch-change-dates
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - termcolor
  - python>=3.7.0
  - requests
  - jupyter
  - pandas
  - pip
  - pip:
      - canvasapi>=2.0.0
